# Generated by Django 3.2.6 on 2022-01-20 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration', models.SmallIntegerField(choices=[(15, '15 Min'), (30, '30 Min'), (45, '45 Min')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attendance_full_name', models.CharField(max_length=255)),
                ('attendance_email_address', models.EmailField(max_length=255)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.slot')),
            ],
        ),
    ]
